import type { SettingFieldDef, SettingsSchema } from './types'
import { DEFAULT_BUILTIN_SHORTCUTS, FONT_OPTIONS, PLUGIN_SUB_FIELDS } from './pluginSubFields'

const bool = (v: boolean) => v
const str = (v: string) => v

const defaultMenuItems = () => ({
  assessments: { toggle: true },
  courses: { toggle: true },
  dashboard: { toggle: true },
  documents: { toggle: true },
  forums: { toggle: true },
  goals: { toggle: true },
  home: { toggle: true },
  messages: { toggle: true },
  myed: { toggle: true },
  news: { toggle: true },
  notices: { toggle: true },
  portals: { toggle: true },
  reports: { toggle: true },
  settings: { toggle: true },
  timetable: { toggle: true },
  welcome: { toggle: true },
})

function pluginField(key: string, label: string, defaultValue: Record<string, unknown>): SettingFieldDef {
  return {
    key,
    label,
    type: 'object',
    defaultValue,
    section: 'plugins',
    subFields: PLUGIN_SUB_FIELDS[key] ?? [],
  }
}

export const bsplusHiddenKeys = [
  'bsplus_token',
  'bsplus_refresh_token',
  'bsplus_client_id',
  'bsplus_user',
  'cloudAccessToken',
  'cloudUsername',
  'plugin.assessments-average.storage.assessments',
  'plugin.assessments-average.storage.weightings',
  'bsplus_cloud_settings_known_remote_updated_at',
  'bsplus_lastCloudPoll',
  'bsplus_pending_theme_ensure_after_cloud',
  'ok',
  'server',
]

export const bsplusHiddenPrefixes = [
  'plugin.global-search.storage.',
  'bsplus.analytics.',
]

export const bsplusSchema: SettingsSchema = {
  hiddenKeys: bsplusHiddenKeys,
  hiddenKeyPrefixes: bsplusHiddenPrefixes,
  sections: [
    { id: 'master', label: 'BetterSEQTA+', description: 'Master switch and cloud sync.' },
    { id: 'appearance', label: 'Appearance' },
    { id: 'navigation', label: 'Navigation & Layout' },
    { id: 'shortcuts', label: 'Shortcuts' },
    { id: 'subjects', label: 'Subjects & News' },
    { id: 'plugins', label: 'Plugins' },
    { id: 'announcements', label: 'Announcements & Privacy', advanced: true, defaultExpanded: true },
    { id: 'developer', label: 'Developer', advanced: true },
    { id: 'pluginStorage', label: 'Plugin Data', advanced: true, description: 'Synced plugin runtime storage blobs.' },
  ],
  fields: [
    // Master
    {
      key: 'onoff',
      label: 'BetterSEQTA+ enabled',
      type: 'boolean',
      defaultValue: bool(true),
      section: 'master',
    },
    {
      key: 'autoCloudSettingsSync',
      label: 'Cloud settings sync',
      type: 'boolean',
      defaultValue: bool(true),
      section: 'master',
      description: 'Automatically upload settings when they change in the extension.',
    },

    // Appearance
    {
      key: 'DarkMode',
      label: 'Dark mode',
      type: 'boolean',
      defaultValue: bool(true),
      section: 'appearance',
    },
    {
      key: 'selectedTheme',
      label: 'Selected theme',
      type: 'string',
      defaultValue: str(''),
      section: 'appearance',
      description: 'BetterSEQTA store theme UUID, or empty for no store theme.',
    },
    {
      key: 'selectedColor',
      label: 'Accent colour',
      type: 'colorOrGradient',
      defaultValue: str('linear-gradient(40deg, rgba(201,61,0,1) 0%, RGBA(170, 5, 58, 1) 100%)'),
      section: 'appearance',
    },
    {
      key: 'originalSelectedColor',
      label: 'Original accent colour',
      type: 'colorOrGradient',
      defaultValue: str(''),
      section: 'appearance',
      advanced: true,
      description: 'Saved before theme preview; restored on cancel.',
    },
    {
      key: 'originalDarkMode',
      label: 'Original dark mode',
      type: 'boolean',
      defaultValue: bool(true),
      section: 'appearance',
      advanced: true,
    },
    {
      key: 'transparencyEffects',
      label: 'Transparency effects',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'appearance',
    },
    {
      key: 'animations',
      label: 'Animations',
      type: 'boolean',
      defaultValue: bool(true),
      section: 'appearance',
    },
    {
      key: 'iconOnlySidebar',
      label: 'Icon-only sidebar',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'appearance',
    },
    {
      key: 'selectedFont',
      label: 'Interface font',
      type: 'enum',
      defaultValue: 'rubik',
      section: 'appearance',
      enumOptions: FONT_OPTIONS,
    },
    {
      key: 'adaptiveThemeColour',
      label: 'Adaptive theme colour',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'appearance',
      advanced: true,
    },
    {
      key: 'adaptiveThemeGradient',
      label: 'Adaptive theme gradient',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'appearance',
      advanced: true,
    },
    {
      key: 'adaptiveThemeColourTransition',
      label: 'Adaptive colour transition',
      type: 'boolean',
      defaultValue: bool(true),
      section: 'appearance',
      advanced: true,
    },

    // Navigation
    {
      key: 'defaultPage',
      label: 'Default page',
      type: 'enum',
      defaultValue: 'home',
      section: 'navigation',
      enumOptions: [
        { value: 'home', label: 'Home' },
        { value: 'dashboard', label: 'Dashboard' },
        { value: 'timetable', label: 'Timetable' },
        { value: 'welcome', label: 'Welcome' },
        { value: 'messages', label: 'Messages' },
        { value: 'documents', label: 'Documents' },
        { value: 'reports', label: 'Reports' },
      ],
    },
    {
      key: 'timeFormat',
      label: '12-hour time',
      type: 'enum',
      defaultValue: '24',
      section: 'navigation',
      enumOptions: [
        { value: '12', label: '12-hour' },
        { value: '24', label: '24-hour' },
      ],
    },
    {
      key: 'lessonalert',
      label: 'Home lesson alert',
      type: 'boolean',
      defaultValue: bool(true),
      section: 'navigation',
      hidden: true,
    },
    {
      key: 'menuitems',
      label: 'Sidebar layout',
      type: 'menuLayout',
      defaultValue: defaultMenuItems(),
      section: 'navigation',
      description: 'Drag to reorder menu items and toggle visibility.',
    },
    {
      key: 'menuorder',
      label: 'Menu order',
      type: 'stringList',
      defaultValue: [],
      section: 'navigation',
      hidden: true,
    },
    {
      key: 'defaultmenuorder',
      label: 'Default menu order',
      type: 'stringList',
      defaultValue: [],
      section: 'navigation',
      hidden: true,
    },

    // Shortcuts
    {
      key: 'shortcuts',
      label: 'Built-in shortcuts',
      type: 'toggleList',
      defaultValue: DEFAULT_BUILTIN_SHORTCUTS,
      section: 'shortcuts',
    },
    {
      key: 'customshortcuts',
      label: 'Custom shortcuts',
      type: 'shortcutList',
      defaultValue: [],
      section: 'shortcuts',
      description: 'Custom shortcuts with name, URL, and icon.',
    },

    // Subjects & news
    {
      key: 'subjectfilters',
      label: 'Subject filters',
      type: 'keyValueBooleans',
      defaultValue: {},
      section: 'subjects',
      description: 'Toggle visibility per subject code.',
    },
    {
      key: 'newsSource',
      label: 'News feed source',
      type: 'enum',
      defaultValue: 'australia',
      section: 'subjects',
      enumOptions: [
        { value: 'australia', label: 'Australia' },
        { value: 'usa', label: 'United States' },
        { value: 'uk', label: 'United Kingdom' },
        { value: 'taiwan', label: 'Taiwan' },
        { value: 'hong_kong', label: 'Hong Kong' },
        { value: 'panama', label: 'Panama' },
        { value: 'canada', label: 'Canada' },
        { value: 'singapore', label: 'Singapore' },
        { value: 'japan', label: 'Japan' },
        { value: 'netherlands', label: 'Netherlands' },
      ],
    },

    // Plugin settings
    pluginField('plugin.animated-background.settings', 'Animated background', { enabled: true, speed: 1 }),
    pluginField('plugin.assessments-average.settings', 'Assessments average', { enabled: false, lettergrade: false }),
    pluginField('plugin.notificationCollector.settings', 'Notification collector', { enabled: true }),
    pluginField('plugin.timetable.settings', 'Timetable', { enabled: true }),
    pluginField('plugin.timetableEdit.settings', 'Timetable edit', { enabled: true }),
    pluginField('plugin.global-search.settings', 'Global search', {
      enabled: false,
      searchHotkey: 'ctrl+k',
      showRecentFirst: true,
      transparencyEffects: true,
      runIndexingOnLoad: true,
      passiveIndexing: true,
    }),
    pluginField('plugin.profile-picture.settings', 'Profile picture', { enabled: false, useCloudPfp: false }),
    pluginField('plugin.messageFolders.settings', 'Message folders', {
      enabled: true,
      showTagsInAllMessages: true,
      hideFolderedMessagesInAll: true,
    }),
    pluginField('plugin.enhanced-navigation.settings', 'Enhanced navigation', { enabled: true, autoScrollOnClick: false }),
    pluginField('plugin.background-music.settings', 'Background music', { enabled: false, volume: 0.5, pauseOnHidden: true }),
    pluginField('plugin.grade-analytics.settings', 'Grade analytics', { cacheTtlHours: 24 }),

    // Plugin storage (advanced)
    {
      key: 'plugin.messageFolders.storage.folders',
      label: 'Message folder definitions',
      type: 'messageFolders',
      defaultValue: [],
      section: 'pluginStorage',
      advanced: true,
    },
    {
      key: 'plugin.messageFolders.storage.messageAssignments',
      label: 'Message folder assignments',
      type: 'json',
      defaultValue: {},
      section: 'pluginStorage',
      advanced: true,
    },
    {
      key: 'plugin.timetableEdit.storage.timetableOverrides',
      label: 'Timetable overrides (by class)',
      type: 'json',
      defaultValue: {},
      section: 'pluginStorage',
      advanced: true,
    },
    {
      key: 'plugin.timetableEdit.storage.timetableOverridesBySubject',
      label: 'Timetable overrides (by subject)',
      type: 'json',
      defaultValue: {},
      section: 'pluginStorage',
      advanced: true,
    },
    {
      key: 'plugin.assessments-average.storage.weightingOverrides',
      label: 'Assessment weighting overrides',
      type: 'json',
      defaultValue: {},
      section: 'pluginStorage',
      advanced: true,
    },
    {
      key: 'plugin.notificationCollector.storage.lastNotificationCount',
      label: 'Last notification count',
      type: 'number',
      defaultValue: 0,
      section: 'pluginStorage',
      advanced: true,
    },
    {
      key: 'plugin.notificationCollector.storage.consecutiveErrors',
      label: 'Notification collector errors',
      type: 'number',
      defaultValue: 0,
      section: 'pluginStorage',
      advanced: true,
    },
    {
      key: 'plugin.notificationCollector.storage.lastCheckedTime',
      label: 'Last notification check',
      type: 'string',
      defaultValue: str(''),
      section: 'pluginStorage',
      advanced: true,
    },

    // Announcements (advanced)
    {
      key: 'themeOfTheMonthDisabled',
      label: 'Theme of the Month',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'announcements',
      advanced: true,
      invert: true,
      description: 'When off, Theme of the Month prompts are shown.',
    },
    {
      key: 'themeOfTheMonthDismissedMonth',
      label: 'Theme of the Month dismissed month',
      type: 'month',
      defaultValue: str(''),
      section: 'announcements',
      advanced: true,
    },
    {
      key: 'themeOfTheMonthLastSeenId',
      label: 'Theme of the Month last seen ID',
      type: 'string',
      defaultValue: str(''),
      section: 'announcements',
      advanced: true,
      description: 'Deprecated; kept for compatibility.',
    },
    {
      key: 'privacyStatementShown',
      label: 'Privacy statement shown',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'announcements',
      advanced: true,
    },
    {
      key: 'privacyStatementLastUpdated',
      label: 'Privacy statement last updated',
      type: 'string',
      defaultValue: str(''),
      section: 'announcements',
      advanced: true,
    },
    {
      key: 'engageParentsAnnouncementShown',
      label: 'Engage parents announcement shown',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'announcements',
      advanced: true,
    },
    {
      key: 'bsCloudAutoSyncAnnouncementShown',
      label: 'Cloud auto-sync announcement shown',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'announcements',
      advanced: true,
    },
    {
      key: 'justupdated',
      label: 'Just updated flag',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'announcements',
      advanced: true,
    },
    {
      key: 'profile_picture_revision',
      label: 'Profile picture revision',
      type: 'number',
      defaultValue: 0,
      section: 'announcements',
      advanced: true,
      description: 'Counter for PFP refresh; not the image itself.',
    },
    {
      key: 'lastSeenNightlyPublishedAt',
      label: 'Last seen nightly release',
      type: 'string',
      defaultValue: str(''),
      section: 'announcements',
      advanced: true,
    },

    // Developer (requires devMode)
    {
      key: 'devMode',
      label: 'Developer mode',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'developer',
      requiresDev: false,
      description: 'Unlock developer options below.',
    },
    {
      key: 'hideSensitiveContent',
      label: 'Hide sensitive content',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'developer',
      requiresDev: true,
    },
    {
      key: 'mockNotices',
      label: 'Mock notices',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'developer',
      requiresDev: true,
    },
    {
      key: 'devGhReleaseVersionOverride',
      label: 'GitHub release version override',
      type: 'string',
      defaultValue: str(''),
      section: 'developer',
      requiresDev: true,
      description: 'Semver string for testing update flows.',
    },
  ],
}
