import type { SettingsSchema } from './types'

const bool = (v: boolean) => v
const str = (v: string) => v

export const desqtaSchema: SettingsSchema = {
  hiddenKeys: [
    'cloud_settings_server_revision',
    'cloud_settings_server_updated_at',
    'last_synced_cloud_pfp_url',
    'dashboard_widgets_layout',
    'sidebar_recent_activity',
    'ok',
    'server',
  ],
  sections: [
    { id: 'shortcuts', label: 'Shortcuts', description: 'Custom quick links on the homepage.' },
    { id: 'feeds', label: 'RSS Feeds', description: 'RSS feed URLs for the news widget.' },
    { id: 'homepage', label: 'Homepage', description: 'Weather and location preferences.' },
    { id: 'notifications', label: 'Notifications' },
    { id: 'display', label: 'Display', description: 'Theme, accent colour, and zoom.' },
    { id: 'performance', label: 'Performance' },
    { id: 'ai', label: 'AI Integrations' },
    { id: 'sidebar', label: 'Sidebar', description: 'Collapse and expand behaviour.' },
    { id: 'cloud', label: 'Cloud & Privacy' },
    { id: 'language', label: 'Language' },
    { id: 'desktop', label: 'Desktop' },
    { id: 'dashboard', label: 'Dashboard' },
    { id: 'customBackground', label: 'Custom Background', advanced: true },
    { id: 'themes', label: 'Themes', advanced: true, description: 'Downloaded theme metadata (assets stay on device).' },
    { id: 'onboarding', label: 'Onboarding', advanced: true },
    { id: 'developer', label: 'Developer Settings', advanced: true },
  ],
  fields: [
    // Shortcuts
    {
      key: 'shortcuts',
      label: 'Shortcuts',
      type: 'shortcutList',
      defaultValue: [],
      section: 'shortcuts',
      description: 'Custom shortcuts with name, icon, and URL.',
    },

    // Feeds
    {
      key: 'feeds',
      label: 'RSS feeds',
      type: 'feedList',
      defaultValue: [],
      section: 'feeds',
    },
    {
      key: 'separate_rss_feed',
      label: 'Separate RSS feed widget',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'feeds',
    },

    // Homepage
    {
      key: 'weather_enabled',
      label: 'Weather widget',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'homepage',
    },
    {
      key: 'weather_city',
      label: 'Weather city',
      type: 'string',
      defaultValue: str(''),
      section: 'homepage',
      visibleWhen: (d) => d.weather_enabled === true,
    },
    {
      key: 'weather_country',
      label: 'Weather country',
      type: 'string',
      defaultValue: str(''),
      section: 'homepage',
      visibleWhen: (d) => d.weather_enabled === true,
    },
    {
      key: 'force_use_location',
      label: 'Use device location for weather',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'homepage',
      visibleWhen: (d) => d.weather_enabled === true,
    },

    // Notifications
    {
      key: 'reminders_enabled',
      label: 'Reminders',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'notifications',
    },
    {
      key: 'auto_dismiss_message_notifications',
      label: 'Auto-dismiss message notifications',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'notifications',
    },

    // Display
    {
      key: 'theme',
      label: 'Theme mode',
      type: 'enum',
      defaultValue: 'dark',
      section: 'display',
      enumOptions: [
        { value: 'light', label: 'Light' },
        { value: 'dark', label: 'Dark' },
        { value: 'system', label: 'System' },
      ],
    },
    {
      key: 'accent_color',
      label: 'Accent colour',
      type: 'color',
      defaultValue: '#3b82f6',
      section: 'display',
    },
    {
      key: 'disable_school_picture',
      label: 'Show school picture',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'display',
      invert: true,
      description: 'When off, the school picture is hidden.',
    },
    {
      key: 'zoom_level',
      label: 'UI zoom',
      type: 'number',
      defaultValue: null,
      section: 'display',
      min: 0.5,
      max: 2.0,
      step: 0.1,
      useSlider: true,
      description: 'Scale from 0.5 to 2.0. Leave empty for default (1.0).',
    },

    // Performance
    {
      key: 'enhanced_animations',
      label: 'Enhanced animations',
      type: 'boolean',
      defaultValue: bool(true),
      section: 'performance',
    },

    // AI
    {
      key: 'ai_integrations_enabled',
      label: 'AI integrations',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'ai',
    },
    {
      key: 'ai_provider',
      label: 'AI provider',
      type: 'enum',
      defaultValue: 'gemini',
      section: 'ai',
      enumOptions: [
        { value: 'gemini', label: 'Gemini' },
        { value: 'cerebras', label: 'Cerebras' },
      ],
      visibleWhen: (d) => d.ai_integrations_enabled === true,
    },
    {
      key: 'gemini_api_key',
      label: 'Gemini API key',
      type: 'password',
      defaultValue: null,
      section: 'ai',
      visibleWhen: (d) => d.ai_integrations_enabled === true && d.ai_provider !== 'cerebras',
    },
    {
      key: 'cerebras_api_key',
      label: 'Cerebras API key',
      type: 'password',
      defaultValue: null,
      section: 'ai',
      visibleWhen: (d) => d.ai_integrations_enabled === true && d.ai_provider === 'cerebras',
    },
    {
      key: 'lesson_summary_analyser_enabled',
      label: 'Lesson summary analyser',
      type: 'boolean',
      defaultValue: bool(true),
      section: 'ai',
      visibleWhen: (d) => d.ai_integrations_enabled === true,
    },
    {
      key: 'quiz_generator_enabled',
      label: 'Quiz generator',
      type: 'boolean',
      defaultValue: bool(true),
      section: 'ai',
      visibleWhen: (d) => d.ai_integrations_enabled === true,
    },
    {
      key: 'grade_analyser_enabled',
      label: 'Grade analyser',
      type: 'readOnly',
      defaultValue: bool(true),
      section: 'ai',
      hidden: true,
      description: 'No user-facing control — read only.',
    },

    // Sidebar
    {
      key: 'menu_order',
      label: 'Sidebar layout',
      type: 'sidebarLayout',
      defaultValue: null,
      section: 'sidebar',
      description: 'Drag to reorder pages and toggle visibility.',
    },
    {
      key: 'sidebar_folders',
      label: 'Sidebar folders',
      type: 'sidebarFolders',
      defaultValue: null,
      section: 'sidebar',
    },
    {
      key: 'sidebar_favorites',
      label: 'Sidebar favourites',
      type: 'stringList',
      defaultValue: null,
      section: 'sidebar',
    },
    {
      key: 'disabled_sidebar_pages',
      label: 'Disabled sidebar pages',
      type: 'stringList',
      defaultValue: null,
      section: 'sidebar',
      hidden: true,
    },
    {
      key: 'auto_collapse_sidebar',
      label: 'Auto-collapse sidebar',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'sidebar',
    },
    {
      key: 'auto_expand_sidebar_hover',
      label: 'Expand sidebar on hover',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'sidebar',
    },

    // Cloud & privacy
    {
      key: 'accepted_cloud_eula',
      label: 'Accepted cloud EULA',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'cloud',
    },
    {
      key: 'send_anonymous_usage_statistics',
      label: 'Send anonymous usage statistics',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'cloud',
    },
    {
      key: 'sync_cloud_pfp',
      label: 'Sync profile picture to cloud',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'cloud',
    },
    {
      key: 'biometric_enabled',
      label: 'Biometric unlock (mobile)',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'cloud',
    },

    // Language
    {
      key: 'language',
      label: 'Language',
      type: 'enum',
      defaultValue: 'en',
      section: 'language',
      enumOptions: [
        { value: 'en', label: 'English' },
        { value: 'es', label: 'Spanish' },
        { value: 'fr', label: 'French' },
        { value: 'de', label: 'German' },
        { value: 'zh', label: 'Chinese' },
        { value: 'ja', label: 'Japanese' },
        { value: 'ko', label: 'Korean' },
        { value: 'pt', label: 'Portuguese' },
        { value: 'it', label: 'Italian' },
        { value: 'nl', label: 'Dutch' },
        { value: 'pl', label: 'Polish' },
        { value: 'ru', label: 'Russian' },
        { value: 'ar', label: 'Arabic' },
        { value: 'hi', label: 'Hindi' },
        { value: 'vi', label: 'Vietnamese' },
      ],
    },

    // Desktop
    {
      key: 'minimize_to_tray',
      label: 'Minimize to system tray',
      type: 'boolean',
      defaultValue: bool(true),
      section: 'desktop',
    },

    // Global search (shown in its own implicit section via dashboard grouping - use dashboard section)
    {
      key: 'global_search_enabled',
      label: 'Global search',
      type: 'boolean',
      defaultValue: bool(true),
      section: 'dashboard',
    },
    {
      key: 'dashboard_today_schedule_fit_width',
      label: 'Today schedule fits width',
      type: 'boolean',
      defaultValue: bool(true),
      section: 'dashboard',
    },

    // Custom background (advanced)
    {
      key: 'custom_background_enabled',
      label: 'Custom background',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'customBackground',
      advanced: true,
    },
    {
      key: 'custom_background_fit',
      label: 'Background fit',
      type: 'enum',
      defaultValue: 'cover',
      section: 'customBackground',
      advanced: true,
      enumOptions: [
        { value: 'cover', label: 'Cover' },
        { value: 'contain', label: 'Contain' },
        { value: 'fill', label: 'Fill' },
      ],
      visibleWhen: (d) => d.custom_background_enabled === true,
    },
    {
      key: 'custom_background_opacity',
      label: 'Background opacity',
      type: 'number',
      defaultValue: 1.0,
      section: 'customBackground',
      advanced: true,
      min: 0.2,
      max: 1.0,
      step: 0.05,
      visibleWhen: (d) => d.custom_background_enabled === true,
    },
    {
      key: 'custom_background_dim',
      label: 'Background dim',
      type: 'number',
      defaultValue: 0.0,
      section: 'customBackground',
      advanced: true,
      min: 0.0,
      max: 0.8,
      step: 0.05,
      visibleWhen: (d) => d.custom_background_enabled === true,
    },

    // Themes (advanced)
    {
      key: 'current_theme',
      label: 'Current theme pack',
      type: 'string',
      defaultValue: 'default',
      section: 'themes',
      advanced: true,
      description: 'Named theme pack slug from the theme store.',
    },
    {
      key: 'downloaded_theme_ids',
      label: 'Downloaded theme IDs',
      type: 'stringList',
      defaultValue: null,
      section: 'themes',
      advanced: true,
    },
    {
      key: 'downloaded_theme_metadata',
      label: 'Downloaded theme metadata',
      type: 'readOnly',
      defaultValue: null,
      section: 'themes',
      advanced: true,
      description: 'Managed by the theme store on your device; synced as metadata only.',
    },

    // Onboarding (advanced)
    {
      key: 'has_been_through_onboarding',
      label: 'Completed onboarding',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'onboarding',
      advanced: true,
    },
    {
      key: 'has_completed_setup_assistant',
      label: 'Completed setup assistant',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'onboarding',
      advanced: true,
    },
    {
      key: 'has_completed_post_login_prompts',
      label: 'Completed post-login prompts',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'onboarding',
      advanced: true,
    },

    // Developer
    {
      key: 'dev_sensitive_info_hider',
      label: 'Hide sensitive information',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'developer',
      advanced: true,
      description: 'Masks PII in the UI for demos and screenshots.',
    },
    {
      key: 'dev_force_offline_mode',
      label: 'Force offline mode',
      type: 'boolean',
      defaultValue: bool(false),
      section: 'developer',
      advanced: true,
      description: 'Skips cloud settings download.',
    },
  ],
}
